name: ImpactTNT
main: com.github.etsija.impacttnt.ImpactTNT
version: 0.2
depend: [BKCommonLib]
commands:
    impact:
        description: This command sets TNT in hand to "impact" mode, ie. creates ImpactTNT
        usage: Hold TNT in your hand and type /<command>
        permission: impacttnt.create
        permission-message: You don't have <permission> permission.